# Generated by Django 5.0.6 on 2024-05-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complated',
            new_name='completed',
        ),
    ]
