# Generated by Django 4.2.11 on 2024-04-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
    ]
